stages:
  - build
  - test
  - review

variables:
 DATABASE_URL: 'mongodb://mongo/user_posts'
before_script:
- cd reddit
- apt-get update && apt-get install -y mongodb-server ruby-full ruby-dev build-essential git && gem install bundler

build_job:
  stage: build
  script:
    - echo 'Building'

# test_unit_job:
#  stage: test
#  services:
#  - mongo:latest
#  script:
#  - ruby simpletest.rb

test_integration_job:
  stage: test
  script:
    - echo 'Testing 2'

deploy_dev_job:
  stage: review
  script:
    - echo 'Deploy'
  environment:
    name: dev
    url: http://dev.example.com

