FROM python:3.6.0-alpine

WORKDIR /app
COPY . ./

# Слой костыль, иначе   Requested MarkupSafe>=2.0  but installing version None
RUN pip install --upgrade pip && \
    pip3 install flask==0.12.3

RUN apk --no-cache --update add build-base=0.4-r1 && \
    pip install -r requirements.txt && \
    apk del build-base


ENV POST_DATABASE_HOST post_db
ENV POST_DATABASE posts

ENTRYPOINT ["python3", "post_app.py"]
