version: '3.3'

services:
  mongo_db:
    image: mongo:${MONGO_VERSION:-3.2}
    volumes:
      - mongo_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db

  ui:
    image: ${USER_NAME:-user}/ui:${APP_TAG:-latest}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED:-false}
    ports:
      - ${UI_PUBLISHED_PORT:-9292}:9292/tcp
    networks:
      - front_net
    depends_on:
      - post
      - comment
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:${FLUENTD_PUBLISHED_PORT:-24224}
        tag: service.ui

  post:
    image: ${USER_NAME:-user}/post:${APP_TAG:-latest}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED:-false}
    networks:
      - back_net
      - front_net
    depends_on:
      - mongo_db
    ports:
      - 5000:5000/tcp
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:${FLUENTD_PUBLISHED_PORT:-24224}
        tag: service.post

  comment:
    image: ${USER_NAME:-user}/comment:${APP_TAG:-latest}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED:-false}
    networks:
      - back_net
      - front_net
    depends_on:
      - mongo_db
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:${FLUENTD_PUBLISHED_PORT:-24224}
        tag: service.comment

volumes:
  mongo_db:

networks:
  back_net:
    ipam:
      config:
        - subnet: ${BACK_SUBNET:-10.0.2.0/24}
  front_net:
    ipam:
      config:
        - subnet: ${FRONT_SUBNET:-10.0.1.0/24}
