version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - back-network
  ui:
    build: ./ui
    image: ${USERNAME}/${UI_VERSION}
    ports:
      - ${UI_PORT}
    networks:
      - front-network
  post:
    build: ./post-py
    image: ${USERNAME}/post:2.0
    networks:
      - back-network
      - front-network
  comment:
    build: ./comment
    image: ${USERNAME}/comment:1.0
    networks:
      - back-network
      - front-network

volumes:
  post_db:

networks:
  back-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.2.0/24
  front-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.1.0/2
